language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pycodestyle pep257 pytest
script:
  - python setup.py test
  - pycodestyle --ignore=E501,E741,W503 *.py boatwright tests
  - pep257 *.py boatwright tests
